AWSTemplateFormatVersion: '2010-09-09'

Resources:

  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cloudformation-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Deny
                Action:
                  - 'budgets:*'
                  - 'aws-portal:*'
                Resource: '*'
              -
                Effect: Allow
                Action: '*'
                Resource: '*'

  CloudformationUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user"
      Policies:
        -
          PolicyName: cloudformation-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - cloudformation:*
                Resource: '*'
              -
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudformationRole.Arn
              -
                Effect: Allow
                Action:
                  - iam:*
                  - s3:*
                Resource: '*'

  CloudFormationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref CloudformationUser


Outputs:

  CloudformationRole:
    Description: 'Cloudformation Role ARN'
    Value: !GetAtt CloudformationRole.Arn

  CloudformationAccessKey:
    Description: 'Cloudformation User Access Key'
    Value: !Ref CloudFormationUserAccessKey

  CloudformationSecretKey:
    Description: 'Cloudformation User Secret Key'
    Value: !GetAtt CloudFormationUserAccessKey.SecretAccessKey